const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'Chưa xác định';
let ctx,validated,planning,report,generation=0;
function message(t){$('status').textContent=t;}
function save(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function request(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Không nhận được dữ liệu');return j;}
function tab(name){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',b.dataset.tab===name));document.querySelectorAll('[data-pane]').forEach(p=>p.hidden=p.dataset.pane!==name);history.replaceState(null,'','?tab='+encodeURIComponent(name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function metric(label,value,unit,note=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}<small>${esc(unit)}</small></strong><em>${esc(note)}</em></div>`;}
function draw(p,result){
  $('plan-metrics').innerHTML=metric('Tuyến có lượt quay về',n(result.route_length_m),'m','Khoảng cách hình học sơ bộ')+metric('Thời gian danh định',n(result.nominal_duration_s/60),'phút','Di chuyển + dừng đo')+metric('Năng lượng ước tính',n(result.estimated_energy_wh),'Wh','Từ công suất giả định')+metric('Ngân sách đến reserve',n(result.reserve_available_wh),'Wh',result.energy_budget_pass?'Trong ngân sách giả định':'VƯỢT NGÂN SÁCH');
  const points=[{id:'BASE',x_m:0,y_m:0},...p.targets];const xs=points.map(v=>v.x_m),ys=points.map(v=>v.y_m);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const scale=Math.min(470/Math.max(1,maxX-minX),230/Math.max(1,maxY-minY));const x=v=>65+(v-minX)*scale,y=v=>295-(v-minY)*scale;
  let grid='';for(let i=0;i<13;i++)grid+=`<path d="M${30+i*45} 30V325"/>`;for(let i=0;i<8;i++)grid+=`<path d="M30 ${30+i*42}H590"/>`;
  $('route').innerHTML=`<g stroke="#ecece8" stroke-width="1">${grid}</g><polyline points="${[...points,points[0]].map(v=>`${x(v.x_m)},${y(v.y_m)}`).join(' ')}" fill="none" stroke="#181818" stroke-width="2" stroke-dasharray="5 5"/>${points.map((v,i)=>`<circle cx="${x(v.x_m)}" cy="${y(v.y_m)}" r="${i?6:9}" fill="#111"/><circle cx="${x(v.x_m)}" cy="${y(v.y_m)}" r="${i?12:16}" fill="none" stroke="#aaa"/><text x="${x(v.x_m)+17}" y="${y(v.y_m)-14}" font-size="11" font-family="monospace">${esc(v.id)}</text>`).join('')}<text x="32" y="358" font-size="9" fill="#777">ĐƠN VỊ: MÉT / CHƯA CÓ MAP VẬT CẢN</text>`;
  $('point-count').textContent=p.targets.length+' ĐIỂM + BASE';$('targets').innerHTML=p.targets.map(t=>`<div class="target"><code>${esc(t.id)}</code><div>${esc(t.asset)}<small>${n(t.x_m)} / ${n(t.y_m)} m · dừng ${n(p.dwell_s,0)} s</small></div><b>${n(t.max_surface_c,0)}°C</b></div>`).join('');
}
async function updatePlan(){try{const source=$('mission').value;const r=await request('/api/deployment/plan',{mission:JSON.parse(source)});if($('mission').value!==source){message('Nhiệm vụ đổi trong lúc tính. Kiểm lại cấu hình hiện tại.');return false;}validated=r.mission;planning=r.plan;if(!$('evidence-mission-hash').value){$('evidence-mission-hash').value=planning.mission_sha256;$('evidence-cad-revision').value=validated.cad_revision;}draw(validated,planning);message('Đặc tả hợp lệ / '+planning.mission_sha256.slice(0,12)+' / ngân sách dựa trên giả định.');return true;}catch(e){message('Đã chặn: '+e.message);return false;}}
function hardware(){const a=ctx.registry.actuators[0],g=ctx.hardware_gap;
  $('hardware-metrics').innerHTML=metric('Tham chiếu có tải',n(ctx.cad_metrics.loaded_mass_kg,2),'kg','Motor đại diện 180 g')+metric('Thay riêng khối lượng motor',n(g.candidate_loaded_mass_kg,2),'kg','Chưa đổi gá / dây / cảm biến')+metric('Mục tiêu hiện tại',n(g.target_mass_kg,1),'kg','Cần xem lại kiến trúc')+metric('12 actuator / giá web',n(g.actuator_subtotal_usd,2),'USD','Chưa phải BOM hay báo giá');
  $('actuator').innerHTML=`<div class="sku"><div><p class="eyebrow">${esc(a.manufacturer)} / SKU CỤ THỂ</p><h2>${esc(a.sku)}</h2><p>Thông số do nhà sản xuất công bố, kiểm tra ${esc(ctx.registry.checked_on)}. Chưa đo trên Q4, chưa chọn mua.</p><a href="${esc(a.source)}" target="_blank" rel="noopener">Xem datasheet nhà sản xuất ↗</a></div><table class="hardware-table"><tbody>${[['Khối lượng','380 g'],['Kích thước','Ø79 × 43 mm'],['Mô-men định mức / đỉnh','3 / 9 Nm'],['Điện áp lựa chọn','24 / 48 V'],['Giá web / chiếc','$229.90']].map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody></table></div>`;
  $('hardware-gap').innerHTML=`<div class="gap-line">Khối lượng tăng <b>${n((g.candidate_loaded_mass_kg-ctx.cad_metrics.loaded_mass_kg),2)} kg</b> với 12 motor. Chưa tính phần cứng khác.</div><div class="gap-line">Motor đại diện Ø48 mm; ứng viên Ø79 × 43 mm. <b>Chưa xác nhận lắp vừa.</b> Cần CAD nhà cung cấp, interface và gá mới.</div><div class="gap-line">Giới hạn 8 Nm của mô phỏng không phải mô-men liên tục 3 Nm của actuator. Cần kiểm torque–speed và tải nhiệt từng khớp.</div><div class="gap-line">Giữ dữ liệu phase/motor, tỷ số truyền và mô-men đầu ra đúng hệ đơn vị. Chưa hiệu chuẩn mô hình tương đương.</div>`;
  $('bom').innerHTML=ctx.registry.unpriced_subsystems.map(x=>`<div class="bom-line">${esc(x)} <span class="fail">/ chưa báo giá</span></div>`).join('');
  $('readiness').innerHTML=ctx.readiness.map((v,i)=>`<div class="ready-row"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(v.label)}</strong><p>${esc(v.detail)}</p><b class="fail">CHƯA CÓ BẰNG CHỨNG</b></div>`).join('');
}
function renderReport(r){report=r;const fields={coverage:'Điểm có tham chiếu RGB + nhiệt',media_capture:'Vị trí và tham chiếu ảnh',dwell:'Thời gian dừng đo',sample_gap:'Khoảng cách mẫu',speed:'Tốc độ từ vị trí',battery_reserve:'Pin dự phòng',motor_temperature:'Nhiệt motor',estop_interlock:'Lệnh khi E-stop',return_to_base:'Quay về base',planned_energy:'Ngân sách danh định'};
  $('assessment').innerHTML=`<div class="verdict"><b>${r.declared_log_checks_pass?'Đạt các kiểm số liệu khai báo':'Có kiểm số liệu chưa đạt'}</b><br>Nguồn: ${esc(r.metadata.provenance)} / chưa xác minh độc lập. Chưa cho phép triển khai phần cứng.</div><p class="hash">MISSION ${esc(r.mission_sha256)}<br>CSV ${esc(r.csv_sha256)}</p><p>${n(r.metrics.duration_s/60)} phút · ${n(r.metrics.distance_m)} m · ${n(r.metrics.electrical_energy_wh,3)} Wh tích phân V×I</p>${r.gates.map(g=>`<div class="gate"><div>${esc(fields[g.id])}<span>${esc(g.criterion)}</span></div><b class="${g.passed?'pass':'fail'}">${g.passed?'ĐẠT':'CHƯA ĐẠT'}</b></div>`).join('')}<p class="caption">Chưa nhập/kiểm byte ảnh, giá trị nhiệt radiometric hay chứng chỉ hiệu chuẩn. Nhật ký E-stop không chứng minh cắt nguồn hoặc khoảng cách dừng. ${r.current_source_match===false?'Nguồn phần mềm đã đổi từ lúc ghi báo cáo.':''}</p>`;$('save-report').disabled=false;
}
async function assess(){try{if(!await updatePlan())return;const metadata={provenance:$('provenance').value,hardware_id:$('hardware-id').value,firmware_revision:$('firmware-id').value,operator:$('operator').value,collected_at:$('collected').value,sensor_calibration_id:$('calibration').value,mission_sha256:$('evidence-mission-hash').value,cad_revision:$('evidence-cad-revision').value};const version=generation;const r=await request('/api/deployment/assess',{mission:validated,metadata,csv:$('csv').value});if(version!==generation){message('Đã lưu report của đầu vào trước đó; cần kiểm lại các giá trị vừa sửa.');return;}renderReport(r);message('Đã lưu nhật ký và report có SHA-256 / '+r.id.slice(0,8));}catch(e){message('Đã chặn: '+e.message);}}
$('plan').addEventListener('click',updatePlan);$('assess').addEventListener('click',assess);
$('mission').addEventListener('input',()=>{generation++;validated=null;planning=null;report=null;$('save-report').disabled=true;$('assessment').innerHTML='<p class="empty">Nhiệm vụ đang sửa. Kiểm và nhập lại log theo cấu hình mới.</p>';message('Nhiệm vụ chưa đồng bộ. Các số bên trên là cấu hình hợp lệ gần nhất.');});
$('save-mission').addEventListener('click',async()=>{if(await updatePlan())save('Q4-pilot-mission.json',validated);});
$('context').addEventListener('click',async()=>{try{if(!await updatePlan())return;save('Q4-deployment-LLM-context.json',await request('/api/deployment/llm-context',{mission:validated}));message('Đã xuất context. Dùng LLM bên ngoài; nhập JSON nhiệm vụ trả về để kiểm.');}catch(e){message(e.message);}});
$('save-report').addEventListener('click',()=>{if(report)save('Q4-pilot-evidence-'+report.id+'.json',report);});
$('csv-template').addEventListener('click',()=>save('Q4-pilot-telemetry-template.csv',ctx.log_columns.join(',')+'\n','text/csv'));
for(const [id,target,max] of [['mission-file','mission',32768],['csv-file','csv',1000000]])$(id).addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>max)throw new Error('File vượt giới hạn kích thước');$(target).value=await f.text();generation++;if(target==='mission'){validated=null;planning=null;await updatePlan();}else{$('csv-label').textContent=f.name+' / '+f.size+' bytes';}report=null;$('save-report').disabled=true;$('assessment').innerHTML='<p class="empty">Đầu vào đã đổi. Kiểm lại để tạo bằng chứng mới.</p>';message('Đã nhập '+f.name+'. Chưa kiểm số liệu.');}catch(e){message(e.message);}finally{e.target.value='';}});
$('sample').addEventListener('click',()=>{generation++;if(!planning){message('Kiểm lại nhiệm vụ trước khi nạp mẫu.');return;}$('evidence-mission-hash').value=planning.mission_sha256;$('evidence-cad-revision').value=validated.cad_revision;$('provenance').value='simulation';$('hardware-id').value='SYNTHETIC-NO-HARDWARE';$('firmware-id').value='fixture-v1';$('operator').value='software-fixture';$('calibration').value='NO-SENSOR';$('collected').value=new Date().toISOString();$('csv').value=ctx.log_columns.join(',')+'\n0,0,0,0.9,24,2,25,0,1,,0,,\n1,4,0,0.89,24,3,72,1,1,P01,1,P01/rgb.jpg,P01/thermal.tiff\n2,0,0,0.2,24,2,72,1,1,,0,,\n';$('csv-label').textContent='Fixture tổng hợp cố tình có lỗi tốc độ, nhiệt, pin, E-stop và coverage.';report=null;$('save-report').disabled=true;$('assessment').innerHTML='<p class="empty">Mẫu thử lỗi đã nạp. Bấm kiểm để xem gate chặn.</p>';message('Dữ liệu tổng hợp, không phải đo robot hoặc kết quả MuJoCo.');});
for(const id of ['csv','provenance','hardware-id','firmware-id','operator','calibration','collected','evidence-mission-hash','evidence-cad-revision'])$(id).addEventListener('input',()=>{generation++;report=null;$('save-report').disabled=true;$('assessment').innerHTML='<p class="empty">Đầu vào đã đổi. Cần kiểm lại.</p>';});
try{ctx=await request('/api/deployment/context');$('revision').textContent='CAD '+ctx.cad_revision+' / '+ctx.registry.checked_on;$('mission').value=JSON.stringify(ctx.mission,null,2);$('collected').value=new Date().toISOString();hardware();await updatePlan();$('context').disabled=false;const name=new URLSearchParams(location.search).get('tab');if(['mission','hardware','evidence','roadmap'].includes(name))tab(name);}catch(e){message('Không kết nối được: '+e.message+'. Chạy Python server để dùng workspace.');document.querySelectorAll('button').forEach(b=>{if(!b.dataset.tab)b.disabled=true;});}
