import * as THREE from 'three/webgpu';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=2)=>Number.isFinite(v)?v.toFixed(d):'—';
let context,reference=new URLSearchParams(location.search).get('reference')||'fixture-sensor-v1',candidate,baseline,undo,job,busy=false,dirty=false,upload,generation=0;
function message(t){$('status').textContent=t;}
async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Không nhận được kết quả');return data;}
function save(name,value){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
class Viewer{
 async init(){
  this.renderer=new THREE.WebGPURenderer({antialias:true,forceWebGL:true});await this.renderer.init();this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;$('canvas').append(this.renderer.domElement);
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#111111');this.scene.fog=new THREE.Fog('#111111',500,1400);
  this.camera=new THREE.PerspectiveCamera(34,1,.5,3000);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.minDistance=45;this.controls.maxDistance=1000;
  this.scene.add(new THREE.HemisphereLight('#ffffff','#7b7b80',2.3));
  const key=new THREE.DirectionalLight('#ffffff',3.5);key.position.set(120,220,100);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-150;key.shadow.camera.right=150;key.shadow.camera.top=150;key.shadow.camera.bottom=-150;key.shadow.camera.far=700;key.shadow.bias=-.001;key.shadow.normalBias=.03;this.scene.add(key);
  const rim=new THREE.DirectionalLight('#dddde2',2);rim.position.set(-160,80,-100);this.scene.add(rim);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(1000,1000),new THREE.MeshStandardMaterial({color:'#151515',roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-8.2;floor.receiveShadow=true;this.scene.add(floor);
  const grid=new THREE.GridHelper(320,32,'#383838','#242424');grid.position.y=-8.1;grid.material.transparent=true;grid.material.opacity=.4;this.scene.add(grid);
  this.current=new THREE.Group();this.refs=new THREE.Group();this.old=new THREE.Group();this.scene.add(this.current,this.refs,this.old);this.old.visible=false;
  this.resize=()=>{const rect=$('canvas').getBoundingClientRect();this.renderer.setSize(rect.width,rect.height);this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();};new ResizeObserver(this.resize).observe($('canvas'));this.resize();this.iso();
  this.renderer.setAnimationLoop(()=>{this.controls.update();if(document.visibilityState==='visible')this.renderer.render(this.scene,this.camera);});
 }
 geometry(data){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));g.setIndex(data.indices);g.computeVertexNormals();return g;}
 clear(group){group.traverse(o=>{o.geometry?.dispose();if(o.material)Array.isArray(o.material)?o.material.forEach(m=>m.dispose()):o.material.dispose();});group.clear();}
 add(data,group,color,opacity=1,wire=false){const geo=this.geometry(data);if(wire){const edge=new THREE.EdgesGeometry(geo,22);geo.dispose();const object=new THREE.LineSegments(edge,new THREE.LineBasicMaterial({color,transparent:true,opacity,depthWrite:false}));group.add(object);return;}
  const object=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,metalness:.32,roughness:.32,transparent:opacity<1,opacity,side:THREE.DoubleSide,depthWrite:opacity===1}));object.castShadow=opacity===1;object.receiveShadow=true;group.add(object);
  const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geo,25),new THREE.LineBasicMaterial({color:'#414145',transparent:true,opacity:.3}));group.add(edge);
 }
 result(r){this.clear(this.current);this.clear(this.refs);this.add(r.mesh,this.current,'#e7e7e3');this.add(r.reference_mesh,this.refs,'#737378',.35);this.add(r.carrier_mesh,this.refs,'#393939',.55);this.refs.visible=$('assembly').getAttribute('aria-pressed')==='true';this.iso();}
 preview(feature){if(!feature.mesh){message('Feature chưa có preview tessellation; xem recipe JSON.');return;}this.clear(this.current);this.add(feature.mesh,this.current,feature.op==='sketch'?'#cacaca':'#e7e7e3',feature.op==='sketch'?.8:1);this.refs.visible=false;}
 ghost(r){this.clear(this.old);if(r)this.add(r.mesh,this.old,'#ffffff',.32,true);this.old.visible=$('ghost').getAttribute('aria-pressed')==='true';}
 iso(){this.camera.position.set(160,128,170);this.controls.target.set(0,8,0);this.controls.update();}
 top(){this.camera.position.set(0,280,.1);this.controls.target.set(0,0,0);this.controls.update();}
 fit(){const box=new THREE.Box3().setFromObject(this.current);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const radius=Math.max(size.x,size.y,size.z,40);const direction=this.camera.position.clone().sub(this.controls.target).normalize();this.controls.target.copy(center);this.camera.position.copy(center).addScaledVector(direction,radius*2.1/Math.min(1,this.camera.aspect));this.controls.update();}
}
const viewer=new Viewer();
function pane(name){document.querySelectorAll('[data-pane]').forEach(b=>b.setAttribute('aria-selected',b.dataset.pane===name));document.querySelectorAll('[data-left]').forEach(p=>p.hidden=p.dataset.left!==name);}
document.querySelectorAll('[data-pane]').forEach(b=>b.addEventListener('click',()=>pane(b.dataset.pane)));
function program(){return JSON.parse($('program').value);}
function changed(){generation++;dirty=true;$('adopt').disabled=true;for(const id of ['step-download','package-download','integrate'])$(id).setAttribute('aria-disabled','true');$('drawing').disabled=true;message('Đề xuất đã đổi. Bản dựng đang hiển thị là kết quả trước đó; cần kiểm và dựng lại.');updateDiff();}
function writeProgram(p,source=true){$('program').value=JSON.stringify(p,null,2);if(source){$('proposal-source').value='engineer';$('model-label').value='manual';}renderParameters();renderTree();changed();}
function renderParameters(){try{$('parameter-controls').innerHTML=Object.entries(program().parameters).map(([k,v])=>`<label class="parameter"><span>${esc(k)} / mm</span><input type="number" step="0.1" data-param="${esc(k)}" value="${v}"></label>`).join('');$('parameter-controls').querySelectorAll('[data-param]').forEach(el=>el.addEventListener('input',()=>{try{const p=program();p.parameters[el.dataset.param]=Number(el.value);$('program').value=JSON.stringify(p,null,2);changed();highlightDependents(el.dataset.param);}catch(e){message(e.message);}}));}catch{}}
function highlightDependents(name){try{const p=program(),ids=new Set();for(const f of p.features){if(JSON.stringify(f).includes(name)||['source','sketch','base','tool'].some(k=>ids.has(f[k])))ids.add(f.id);}$('feature-tree').querySelectorAll('[data-feature]').forEach(el=>el.classList.toggle('dependent',ids.has(el.dataset.feature)));}catch{}}
function renderTree(){try{const p=program();$('feature-tree').innerHTML=p.features.map((f,i)=>`<button class="feature-node" data-feature="${esc(f.id)}"><code>${String(i+1).padStart(2,'0')}</code><span>${esc(f.id)}<small>${esc(f.op)}${f.source?' ← '+esc(f.source):''}</small></span></button>`).join('');$('feature-tree').querySelectorAll('[data-feature]').forEach(button=>button.addEventListener('click',()=>{if(dirty){message('Đề xuất đang đổi; dựng lại trước khi xem hình trung gian.');return;}const f=candidate?.features.find(n=>n.id===button.dataset.feature);if(!f){message('Feature chưa được dựng.');return;}viewer.preview(f);$('feature-tree').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));$('view-label').textContent=f.id+' / '+f.op;$('stage-note').textContent='Hình học trung gian từ kernel, chưa phải chi tiết cuối.';}));}catch(e){message('JSON chưa đọc được: '+e.message);}}
async function updateDiff(){if(!baseline){$('diff').innerHTML='<small>Chọn một kết quả làm baseline để so thay đổi. Mẫu ban đầu do kỹ sư viết.</small>';return;}try{const source=$('program').value;const d=await request('/api/design/diff',{reference,before:baseline.program,after:JSON.parse(source)});if(source!==$('program').value)return;$('diff').innerHTML=Object.entries(d.parameters).map(([k,v])=>`<div class="diff-line"><span>${esc(k)}</span><b>${esc(v.before)} → ${esc(v.after)}</b></div>`).join('')+`<small>Feature thêm ${d.added.length} / sửa ${d.changed.length} / bỏ ${d.removed.length}</small>`;}catch(e){$('diff').textContent='Chưa so được: '+e.message;}}
async function loadContext(id){context=await request('/api/design/context?reference='+encodeURIComponent(id));reference=id;const b=context.brief;$('brief-summary').innerHTML=`<p class="reference-stat"><strong>${esc(b.sensor.name)}</strong><br>${esc(b.sensor.provenance)}<br>Nhôm đại diện / density giả định</p>`;$('brief-hash').textContent='brief '+b.brief_sha256;$('reference-interface').value=JSON.stringify(b.sensor.interface,null,2);$('requirements').innerHTML=[['Envelope','100 × 80 × 45 mm'],['Khối lượng','≤180 g / mật độ giả định'],['Tấm nhận gá','4 × Ø5.2 / vị trí cố định'],['Giao diện sensor',b.sensor.interface.mount_holes.length+' lỗ / từ STEP & khai báo'],['Vành vật liệu','2 mm / kiểm hình học'],['Còn thiếu','Tải, FEA, dung sai, vít, thử lắp']].map(([k,v])=>`<div class="rule">${k}<span>${esc(v)}</span></div>`).join('');writeProgram(context.example);message('Đã đọc brief. Mẫu kỹ sư chưa được dựng ở phiên này.');}
function render(r){candidate=r;dirty=false;viewer.result(r);viewer.ghost(baseline);$('view-label').textContent='BREP / '+r.revision;$('stage-revision').textContent=r.revision+' / '+r.proposal_provenance.source;$('stage-title').textContent=r.program.name;$('stage-note').textContent=r.eligible?'Đạt kiểm hình học khai báo. Chưa phát hành chế tạo.':'Có kiểm chưa đạt. Thiết kế baseline được giữ.';
 $('stage-metrics').innerHTML=`<div><span>Khối lượng / giả định</span><strong>${num(r.metrics.mass_kg*1000,1)}<small>g</small></strong></div><div><span>Feature</span><strong>${r.features.length}</strong></div><div><span>Solid / OCCT</span><strong>${r.metrics.solids}</strong></div>`;
 const pass=r.gates.filter(g=>g.passed).length;$('gate-count').textContent=pass+'/'+r.gates.length+' kiểm đạt';
 const labels={valid_single_solid:'Solid hợp lệ',envelope:'Envelope',mass:'Khối lượng giả định',mount_plane:'Mặt chuẩn Z=0',sensor_shift:'Dịch cảm biến',sensor_collision:'Va chạm sensor',receiving_tool_clearance:'Vùng tiếp cận vít',step_roundtrip:'STEP đọc lại'};
 $('gates').innerHTML=r.gates.map(g=>`<details class="gate-detail"><summary class="gate"><span>${esc(labels[g.id]||g.id.replaceAll('_',' '))}</span><b class="${g.passed?'pass':'fail'}">${g.passed?'✓ Đạt':'× Chưa đạt'}</b></summary><p class="caption">${esc(g.requirement)}<br>${esc(typeof g.actual==='object'?JSON.stringify(g.actual):num(g.actual,4))}</p></details>`).join('');
 $('adopt').disabled=!r.eligible||!r.current_sources_match;$('drawing').disabled=false;for(const [id,key] of [['step-download','step'],['package-download','package']]){$(id).href=r.downloads[key];$(id).setAttribute('aria-disabled','false');}
 $('integrate').href='integration.html?design='+r.revision;$('integrate').setAttribute('aria-disabled',r.eligible&&r.current_sources_match?'false':'true');$('pdf-download').href=r.downloads.pdf;$('drawing-frame').src=r.downloads.svg;renderTree();updateDiff();message(r.current_sources_match===false?'Source đã đổi từ lúc dựng; cần chạy lại trước khi chọn baseline.':r.eligible?'Đạt các kiểm geometry / '+num(r.metrics.build_seconds,1)+' s. Đọc các kiểm và giả định trước khi chọn baseline.':'Candidate có kiểm chưa đạt; xem từng gate và sửa đề xuất.');
}
async function loadResult(revision){const r=await request('/api/design/result?revision='+encodeURIComponent(revision));if(r.brief.reference_id!==reference){baseline=null;undo=null;$('undo').disabled=true;await loadContext(r.brief.reference_id);}$('program').value=JSON.stringify(r.program,null,2);$('proposal-source').value=r.proposal_provenance.source;$('model-label').value=r.proposal_provenance.model;renderParameters();render(r);history.replaceState(null,'','?design='+r.revision);}
async function start(){if(busy)return;busy=true;$('build').disabled=true;const version=generation;try{const p=program();await request('/api/design/validate',{reference,program:p});const j=await request('/api/design/start',{reference,program:p,provenance:{source:$('proposal-source').value,model:$('model-label').value,note:'Source declared by importer; no live LLM call in this product.'}});busy=true;job=j;$('build').disabled=true;$('progress').hidden=false;$('progress').removeAttribute('value');poll(version);}catch(e){busy=false;$('build').disabled=false;message('Đã chặn: '+e.message);}}
async function poll(version){try{const j=await request('/api/design/job?id='+job.id);job=j;message(j.message);if(['queued','running'].includes(j.status)){setTimeout(()=>poll(version),1200);return;}busy=false;$('build').disabled=false;$('progress').hidden=true;if(j.status==='completed'){if(j.action==='reference'){baseline=null;candidate=null;undo=null;await loadContext(j.reference_id);viewer.clear(viewer.current);viewer.clear(viewer.refs);viewer.clear(viewer.old);$('stage-metrics').replaceChildren();$('stage-title').textContent='Gá cảm biến.';$('stage-revision').textContent='Reference mới / chưa dựng';$('stage-note').textContent='Dựng chi tiết theo giao diện mới.';$('gates').replaceChildren();$('gate-count').textContent='Chưa có phép kiểm';$('drawing').disabled=true;for(const id of ['step-download','package-download','integrate']){$(id).removeAttribute('href');$(id).setAttribute('aria-disabled','true');}history.replaceState(null,'','?reference='+encodeURIComponent(reference));$('adopt').disabled=true;$('undo').disabled=true;message('STEP đã nhập và kiểm lỗ. Dựng lại gá theo reference mới.');}else if(version===generation){await loadResult(j.revision);history.replaceState(null,'','?design='+j.revision);}else message('Kết quả được lưu trong Phiên thiết kế; đề xuất đã đổi nên chưa thay màn hình.');}}catch(e){busy=false;$('build').disabled=false;$('progress').hidden=true;message(e.message);}}
$('build').addEventListener('click',start);$('program').addEventListener('input',()=>{changed();renderParameters();renderTree();});for(const id of ['proposal-source','model-label'])$(id).addEventListener('input',changed);
$('example').addEventListener('click',()=>writeProgram(context.example));$('shift').addEventListener('click',()=>{try{const p=program();p.parameters.sensor_shift_x=-12;writeProgram(p);}catch(e){message(e.message);}});
$('invalid').addEventListener('click',()=>{try{const p=program();const f=p.features.find(f=>f.id==='carrier_pattern');if(!f)throw new Error('Mẫu thử cần carrier_pattern của gá mẫu');f.translations[0][0]+=5;writeProgram(p);message('Đã cố tình dời một lỗ carrier 5 mm. Dựng để kiểm interface phát hiện lỗi.');}catch(e){message(e.message);}});
$('slot').addEventListener('click',()=>{try{const p=program();if(p.features.some(f=>f.id==='cable_slot'))throw new Error('Đã có rãnh cáp.');const base=p.result;p.features.push({id:'cable_profile',op:'sketch',plane:'XY',origin:['sensor_shift_x',24,-1],profile:{kind:'slot',length:24,width:8}},{id:'cable_tool',op:'extrude',sketch:'cable_profile',amount:'thickness+2'},{id:'cable_slot',op:'boolean',base,tool:'cable_tool',mode:'cut'});p.result='cable_slot';writeProgram(p);}catch(e){message(e.message);}});
$('proposal-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>65536)throw new Error('JSON tối đa 64 KiB');const p=JSON.parse(await file.text());$('program').value=JSON.stringify(p,null,2);$('proposal-source').value='external_llm';$('model-label').value='external / undeclared';renderParameters();renderTree();changed();message('Đã nhập JSON. Chọn đúng nguồn và model; chưa có kiểm hình học.');}catch(e){message(e.message);}finally{e.target.value='';}});
$('llm-context').addEventListener('click',async()=>{try{save('FORGE-feature-LLM-context.json',await request('/api/design/context',{reference,program:program(),intent:$('intent').value,feedback_revision:candidate?.revision||null}));message('Đã xuất context JSON. Dùng LLM bên ngoài rồi nhập đề xuất trả về.');}catch(e){message('Đã chặn: '+e.message);}});
$('step-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2000000){message('STEP tối đa 2 MB');return;}upload=f;$('step-name').textContent=f.name+' / '+f.size+' bytes';});
$('import-reference').addEventListener('click',async()=>{if(busy)return;busy=true;$('build').disabled=true;try{if(!upload)throw new Error('Chọn STEP và khai báo interface trước');const bytes=new Uint8Array(await upload.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));job=await request('/api/design/reference',{name:upload.name,interface:JSON.parse($('reference-interface').value),step_base64:btoa(s)});busy=true;$('build').disabled=true;$('progress').hidden=false;$('progress').removeAttribute('value');poll(generation);}catch(e){busy=false;$('build').disabled=false;message(e.message);}});
$('adopt').addEventListener('click',async()=>{try{await request('/api/design/adopt',{reference,revision:candidate.revision,base_revision:baseline?.revision||null});undo=baseline;baseline=candidate;$('undo').disabled=!undo;viewer.ghost(baseline);updateDiff();message('Đã chọn baseline qua kiểm hình học. Chưa phát hành chế tạo.');}catch(e){message('Chưa áp dụng: '+e.message);}});
$('undo').addEventListener('click',async()=>{if(!undo)return;const previous=undo;undo=baseline;baseline=previous;await loadResult(previous.revision);viewer.ghost(baseline);updateDiff();message('Đã trở về baseline trước; lịch sử candidate vẫn giữ.');});
$('fit').addEventListener('click',()=>viewer.fit());$('top').addEventListener('click',()=>viewer.top());$('iso').addEventListener('click',()=>{if(candidate&&!dirty)render(candidate);else viewer.iso();});
$('assembly').addEventListener('click',()=>{const v=$('assembly').getAttribute('aria-pressed')!=='true';$('assembly').setAttribute('aria-pressed',v);viewer.refs.visible=v;});$('ghost').addEventListener('click',()=>{const v=$('ghost').getAttribute('aria-pressed')!=='true';$('ghost').setAttribute('aria-pressed',v);viewer.old.visible=v;});
$('drawing').addEventListener('click',()=>$('drawing-dialog').showModal());$('drawing-close').addEventListener('click',()=>$('drawing-dialog').close());$('history-close').addEventListener('click',()=>$('history-dialog').close());
$('history-open').addEventListener('click',async()=>{try{const data=await request('/api/design/history');$('history').innerHTML=data.jobs.map(j=>`<button class="history-row" data-job="${esc(j.id)}" ${j.status!=='completed'||j.action!=='build'?'disabled':''}><span>${esc(j.action)} / ${esc(j.status)}<small>${esc(j.message)}</small></span><code>${esc(j.revision||j.id.slice(0,8))}</code></button>`).join('')||'<p class="empty">Chưa có phiên thiết kế. Dựng candidate đầu tiên.</p>';$('history').querySelectorAll('button:not([disabled])').forEach(b=>b.addEventListener('click',async()=>{try{const j=data.jobs.find(j=>j.id===b.dataset.job);await loadResult(j.revision);$('history-dialog').close();}catch(e){message(e.message);}}));$('history-dialog').showModal();}catch(e){message(e.message);}});
try{await viewer.init();await loadContext(reference);const revision=new URLSearchParams(location.search).get('design');if(revision)await loadResult(revision);else if(!new URLSearchParams(location.search).has('reference')){const data=await request('/api/design/history'),recent=data.jobs.find(j=>j.status==='completed'&&j.action==='build'&&j.eligible);if(recent)await loadResult(recent.revision);}}catch(e){message('Không mở được workbench: '+e.message);}
