const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=3)=>Number(v).toFixed(d),q=new URLSearchParams(location.search);
$('design').value=q.get('design')||'';
async function api(url,body){const res=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const r=await res.json();if(!res.ok)throw new Error(r.error);return r;}
function render(r){$('result').hidden=false;$('revision').textContent='Q4 / '+r.revision+' · CAD / '+r.design_revision;$('design').value=r.design_revision;
$('metrics').innerHTML=[['Tải tổng trước',n(r.mass_before_kg)+' kg'],['Tải tổng sau',n(r.mass_after_kg)+' kg'],['Thay đổi',n(r.mass_delta_kg*1000,1)+' g'],['Solid / khớp','49 / 12']].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');
$('mounting').textContent='4 lỗ Ø5.2 trên nắp thật của mô hình Q4, trụ đỡ 6 mm, adapter 8 mm. Gốc gá XYZ: '+r.mounting.origin_mm.map(v=>n(v,1)).join(' / ')+' mm. Vật liệu, sensor và vít cần được kỹ sư xác nhận.';
$('gates').innerHTML=r.gates.map(g=>`<div class="gate"><span>${esc(g.id.replaceAll('_',' '))}<br><small>${esc(g.requirement)}</small></span><b>${g.passed?'✓ Đạt':'× Chưa đạt'}</b></div>`).join('');
$('simulations').innerHTML=r.simulation_summary.map(s=>`<p><b>${esc(s.motion)} / ${n(s.elapsed_simulation_s,1)} s</b><br>${s.summary.fall_detected?'Đã phát hiện ngã':'Không phát hiện ngã trong lượt này'} · ${s.summary.contact_count} chân chịu lực<br>Đây là lượt chạy ngắn, chưa chứng minh độ bền vận hành.</p>`).join('');
$('downloads').innerHTML=[['Robot / vật lý',`/?integrated=${r.revision}&workspace=physics&motion=trot&backend=webgl`],['STEP robot',r.downloads.step],['URDF',r.robot.downloads.urdf],['MJCF',r.robot.downloads.mjcf],['Hồ sơ tích hợp',r.downloads.package],['Dữ liệu mô phỏng',r.downloads.simulation]].map(([a,b])=>`<a href="${esc(b)}" target="_blank" rel="noopener">${a} ↗</a>`).join('');
$('inertial').innerHTML='<table><thead><tr><th>Đại lượng / hệ ROS · SI</th><th>Trước</th><th>Sau</th></tr></thead><tbody>'+[['COM thân / m',r.base_com_before_m,r.base_com_after_m],['Quán tính thân / kg·m²',r.base_inertia_before_kg_m2,r.base_inertia_after_kg_m2]].map(([a,b,c])=>`<tr><td>${a}</td><td>${esc(JSON.stringify(b))}</td><td>${esc(JSON.stringify(c))}</td></tr>`).join('')+'</tbody></table>';
$('limits').innerHTML='<strong>Phạm vi đã kiểm</strong><p>'+(!r.mass_budget_passed?'Vượt ngân sách tải tổng 7 kg. Tải mang còn lại theo ngân sách khối lượng: '+n(r.payload_budget_kg)+' kg; chưa phải tải đã kiểm bền.':'Đạt ngân sách khối lượng khai báo; chưa kiểm bền.')+'</p>'+r.limitations.map(l=>'<p>'+esc(l)+'</p>').join('');
$('robot-view').src=`/?integrated=${r.revision}&workspace=motion&motion=trot&backend=webgl`;
history.replaceState(null,'','?revision='+r.revision);$('status').textContent='Cấu hình đã dựng. '+(r.mass_budget_passed?'Đạt ngân sách khối lượng.':'VƯỢT ngân sách khối lượng; cần giảm tải hoặc thiết kế lại.')+' CAD và robot dùng cùng revision.';}
$('build').addEventListener('click',async()=>{let j;$('build').disabled=true;$('progress').hidden=false;$('status').textContent='Đang kiểm nắp, gá và khối lượng; dựng robot và chạy MuJoCo…';try{j=await api('/api/integration/start',{design_revision:$('design').value.trim()});while(j.status==='running'){await new Promise(r=>setTimeout(r,1200));j=await api('/api/integration/job?id='+j.id);}if(j.status!=='completed')throw new Error(j.error||j.status);render(await api('/api/integration/result?revision='+j.revision));}catch(e){$('status').textContent='Chưa dựng được: '+e.message;}finally{$('build').disabled=false;$('progress').hidden=true;}});
if(q.has('revision'))try{render(await api('/api/integration/result?revision='+encodeURIComponent(q.get('revision'))));}catch(e){$('status').textContent=e.message;}
